export const miPerfilLang = {
  es: {
    'editar': "Editar",
    'quitar':'Quitar',
    'nombreCompleto':'Nombre completo',
    'correoElectronico':'Correo electronico',
    'verificado': 'Verificado',
    'verificar':'Verificar',
    'nombreDelUsuario':'Nombre del usuario',
    'modificar':'Modificar',
    'direccion':'Direccion',
    'contraseña':'Contraseña',
    'cambiarContraseña':'Cambiar contraseña',
    'noEstasLogueado':'No estas logueado',
    'name':'Nuevo nombre de usuario...',
    'direc': 'Nueva Dirección...',
    'pass': 'Nueva Contraseña...',
  },

  en: {
    'editar': "Edit",
    'quitar':'Take off',
    'nombreCompleto':'Full name',
    'correoElectronico':'Email',
    'verificado': 'Verified',
    'verificar':'Verify',
    'nombreDelUsuario':'Username',
    'modificar':'Change',
    'direccion':'Address',
    'contraseña':'Password',
    'cambiarContraseña':'Change password',
    'noEstasLogueado':'You are not logged in',
    'name':'New UserName...',
    'direc': 'New Direction...',
    'pass': 'New Password...',
  },
};
